#Convertisseur de valeur en secondes vers Heure / Minute / Seconde
#nmb_h nmb_m et nmb_s sont les objectifs (nombres d'heures / de minutes / secondes)
total_sec = input("Quel est le nombre de secondes à transformer en heures / minutes / secondes ?")
total_sec = int(total_sec)
nmb_h = (total_sec // 3600 )
rest_h = (total_sec % 3600 )
#nmb_h = str(nmb_h)
#rest_h = str(rest_h)
#print(nmb_h + "est le nombres d'heures et " + rest_h + " est le nombre de secondes restant")
nmb_m = (rest_h // 60)
rest_m = (rest_h % 60)
rest_m = str(rest_m)
nmb_m = str(nmb_m)
nmb_h = str(nmb_h)
print("La durée demandée se découpe en "+ nmb_h + "heures, " + nmb_m + "minutes et "+ rest_m + "secondes")